package view;

import controller.StudentController;
import entity.Student;

import javax.swing.*;
import java.awt.*;

public class AddStudentPage extends JFrame {
    private JTextField nameField, emailField, phoneField, addressField;
    private StudentController studentController;
    private AdminStudentsManagementPage adminStudentsManagementPage;

    public AddStudentPage(AdminStudentsManagementPage adminStudentsManagementPage, StudentController studentController) {
        this.adminStudentsManagementPage = adminStudentsManagementPage;
        this.studentController = studentController; // Controller passed from the management page.
        setTitle("Add Student");
        setLayout(new GridBagLayout());
        initializeUI();
        setSize(800, 450);
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void initializeUI() {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.gridx = 0;

        add(createLabel("Name:"), gbc);
        nameField = createTextField();
        add(nameField, gbc);

        add(createLabel("Email:"), gbc);
        emailField = createTextField();
        add(emailField, gbc);

        add(createLabel("Phone:"), gbc);
        phoneField = createTextField();
        add(phoneField, gbc);

        add(createLabel("Address:"), gbc);
        addressField = createTextField();
        add(addressField, gbc);

        JButton addButton = new JButton("Add");
        addButton.addActionListener(e -> addStudent());
        JButton cancelButton = new JButton("Cancel");
        cancelButton.addActionListener(e -> dispose());

        JPanel buttonPanel = new JPanel(new FlowLayout());
        buttonPanel.add(addButton);
        buttonPanel.add(cancelButton);
        add(buttonPanel, gbc);
    }

    private JLabel createLabel(String text) {
        return new JLabel(text);
    }

    private JTextField createTextField() {
        return new JTextField(20);
    }

    private void addStudent() {
        Student student = new Student(
            0, // Student ID is auto-generated by the database.
            "",
            "",
            "ROLE_STUDENT",
            nameField.getText(),
            emailField.getText(),
            phoneField.getText(),
            addressField.getText()
        );
        if (studentController.addStudent(student)) {
            JOptionPane.showMessageDialog(this, "Student added successfully!");
            adminStudentsManagementPage.refreshTable();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add student.");
        }
    }
}